#!/usr/bin/env bash
#
#########################
#
# Copyright (C) 2019 Vittorio Cagnetta
#
# Author: Vittorio Cagnetta <vaisarger@gmail.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 3 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program, 
# called, in this distribution, "bashkaraoke-LICENSE"; if not, write to the 
# Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA.
#
#########################
#

# ${DESTDIR} should be set throught "export DESTDIR=..." in debian/rules while packaging, or take it from the first command-line argument
[ -z "${DESTDIR}" ] && DESTDIR=$1
#the script should work fine even if DESTDIR is not set

BK_VERSION_NUMBER="10.1.1"

export system_bk_dir="${DESTDIR}/usr/share/bashkaraoke"
export path_dir="${DESTDIR}/usr/bin"
export LIB_URL="https://github.com/BashGui/easybashgui/tags"
export MIN_LIB_VERSION_REQUIRED="4.0.3"

DOCDIR="${DESTDIR}/usr/share/doc/bashkaraoke" 

#
#############################################
# CHECKS
# ...lang?
lang="$(set | grep 'LANG=' | cut -d '=' -f 2 )"
if [ ${#lang} -gt 0 ]
	then
	l="$(if [ $(echo -n "${lang}" | grep -i "it" | wc -c) -gt 0 ]
		then
		echo "IT"
	else
		echo "EN"
	fi )"
else
	l="EN"
fi
export l
#
# ...are we in source directory?
if [ ! -d "src/bashkaraoke_FILES" ]
	then
	[ "${l}" = "IT" ] && echo -e "Devi lanciare questo programma \n nella cartella dei sorgenti \n di bashkaraoke. \n\n Per favore, \n digita \"cd /percorso/alla/cartella/dei/sorgenti\", \n quindi rilancia questo programma."
	[ "${l}" = "EN" ] && echo -e "You must launch this program \n in bashkaraoke source directory. \n\n Please, \n type \"cd /path/to/source\" , \n then relaunch this program."

#   we don't need 3 seconds to read errors in buildlog
#	sleep 3

	exit 1
fi

#
# ...am I root?

# fakeroot should provide fake root privileges, but let's check anyway

if [ "$(whoami)" != "root" ]
	then
	[ "${l}" = "IT" ] && echo -e "\nDevi essere \"root\". \n\n Per favore, apri un terminale, digita \"su\", quindi rilancia questo programma..."
	[ "${l}" = "EN" ] && echo -e "\nYou must be \"root\". \n\n Please, open a terminal, type \"su\", then relaunch this program..."
	
	#   we don't need 3 seconds to read errors in buildlog
	#sleep 3
	
	exit 1
fi

#
# ...easybashgui?

#..and of course we have easybashgui, because b!k depends on it. but let's check anyway

if [ $(echo -n "$(type "easybashgui" 2>/dev/null)" | wc -c ) -eq 0 ]
	then
	[ "${l}" = "IT" ] && echo -e "Sembra che non hai \"easybashgui\" nel tuo sistema \n oppure la libreria \"easybashgui\" non si trova nel path...\n\n\n Per favore, scaricala da ${LIB_URL}, copiala nel tuo path ( p.es.: in /usr/local/bin/ ), e linkala in questo modo: \"ln -s /usr/local/bin/easybashgui_?.?.? /usr/local/bin/easybashgui\" ." 1>&2
	[ "${l}" = "EN" ] && echo -e "It seems you don't have \"easybashgui\" in your system \n or \"easybashgui\" library isn't in your path ...\n\n\n Please, download it from ${LIB_URL}, copy it in your path (e.g.: in /usr/local/bin/ ), and link it in this way: \"ln -s /usr/local/bin/easybashgui_?.?.? /usr/local/bin/easybashgui\" ." 1>&2
	
	#   we don't need 3 seconds to read errors in buildlog
	#sleep 3
	
	exit 1
else
	# Ok, easybashgui exists... let's check min required version...
	: MIN_LIB_VERSION_REQUIRED
	source easybashgui
	: LIB_VERSION
	IFS=$'. \t\n'
	array_LIB_VERSION=( $(echo -n "${LIB_VERSION}" ) )
	array_MIN_LIB_VERSION_REQUIRED=( $(echo -n "${MIN_LIB_VERSION_REQUIRED}" ) )
	IFS=$' \t\n'
	#
	if [ ${array_LIB_VERSION[0]} -gt ${array_MIN_LIB_VERSION_REQUIRED[0]} ]
		then
		obsolete_lib="NO"
	elif [ ${array_LIB_VERSION[0]} -lt ${array_MIN_LIB_VERSION_REQUIRED[0]} ]
		then
		obsolete_lib="YES"
	elif [ ${array_LIB_VERSION[0]} -eq ${array_MIN_LIB_VERSION_REQUIRED[0]} ]
		then
		if [ ${array_LIB_VERSION[1]} -gt ${array_MIN_LIB_VERSION_REQUIRED[1]} ]
			then
			obsolete_lib="NO"
		elif [ ${array_LIB_VERSION[1]} -lt ${array_MIN_LIB_VERSION_REQUIRED[1]} ]
			then
			obsolete_lib="YES"
		elif [ ${array_LIB_VERSION[1]} -eq ${array_MIN_LIB_VERSION_REQUIRED[1]} ]
			then
			if [ ${array_LIB_VERSION[2]} -gt ${array_MIN_LIB_VERSION_REQUIRED[2]} ]
				then
				obsolete_lib="NO"
			elif [ ${array_LIB_VERSION[2]} -lt ${array_MIN_LIB_VERSION_REQUIRED[2]} ]
				then
				obsolete_lib="YES"
			elif [ ${array_LIB_VERSION[2]} -eq ${array_MIN_LIB_VERSION_REQUIRED[2]} ]
				then
				obsolete_lib="NO"
				# perche' le due versioni sono ESATTAMENTE identiche...
			fi
			#
		fi #if [ ${array_LIB_VERSION[1]} -gt ${array_MIN_LIB_VERSION_REQUIRED[1]} ]
		#
	fi #if [ ${array_LIB_VERSION[0]} -gt ${array_MIN_LIB_VERSION_REQUIRED[0]} ]
	#
	if [ "${obsolete_lib}" = "YES" ]
		then
		
		#let's comment all the windows style installation dialog while packaging
		#[ "${l}" = "IT" ] && alert_message "Sembra \n che hai \n una versione \n di \"easybashgui\" \n nel tuo sistema \n inferiore \n alla ${MIN_LIB_VERSION_REQUIRED}\n...\n\n\n\n\n Per favore, \n scarica da \n ${LIB_URL} \n una versione \n recente \n di \"easybashgui\" \n e installala \n prima \n di lanciare \n il programma... :("
		#[ "${l}" = "EN" ] && alert_message "It seems \n you have \n an \"easybashgui\" \n version \n in your system \n prior \n to ${MIN_LIB_VERSION_REQUIRED}\n...\n\n\n\n\n Please, \n download from \n ${LIB_URL} \n a recent \n \"easybashgui\" \n version \n and install it \n first... :("
		
		#echo will work anyway
		[ "${l}" = "IT" ] && echo -e "Sembra \n che hai \n una versione \n di \"easybashgui\" \n nel tuo sistema \n inferiore \n alla ${MIN_LIB_VERSION_REQUIRED}\n...\n\n\n\n\n Per favore, \n scarica da \n ${LIB_URL} \n una versione \n recente \n di \"easybashgui\" \n e installala \n prima \n di lanciare \n il programma... :("
		[ "${l}" = "EN" ] && echo -e "It seems \n you have \n an \"easybashgui\" \n version \n in your system \n prior \n to ${MIN_LIB_VERSION_REQUIRED}\n...\n\n\n\n\n Please, \n download from \n ${LIB_URL} \n a recent \n \"easybashgui\" \n version \n and install it \n first... :("
		
		clean_temp
		
		exit 1
	fi
fi
#
#
#############################################
#
# PHEWWWWWW!!!... EVERYTHING'S OK!!!    :-)
#sleep 1 # ...let's go ahead: only *4* steps :
# 1)
for file in "src/bashkaraoke" "src/hyperkar" "src/xtermkar" "src/bashkaraoke_FILES/bashkaraoke_COMMON" "src/bashkaraoke_FILES/bashkaraoke_CORE" "src/bashkaraoke_FILES/bashkaraoke_OUT" "src/bashkaraoke_FILES/bashkaraoke_EXTRACTOR"
	do
	chmod 755 "${file}"
done && chmod 644 src/bashkaraoke_FILES/*.xpm src/bashkaraoke_FILES/*.png src/bashkaraoke_FILES/*.svg
#
# 2)

#we need also to creare the /usr/bin and /usr/share/doc/bashkaraoke directory while packaging
mkdir -p "${path_dir}"
mkdir -p "${DOCDIR}"

mkdir -p "${system_bk_dir}"
#
# 3)
cp -fR "src/bashkaraoke_FILES" "${system_bk_dir}/" ; chmod 777 "${system_bk_dir}/bashkaraoke_FILES"
cp -fR "src/realtime_dialog_0.2" "${system_bk_dir}/" ; chmod 777 "${system_bk_dir}/realtime_dialog_0.2" ; chmod 755 "${system_bk_dir}/realtime_dialog_0.2/realtime_dialog.py"
#
# 4)
cp "src/bashkaraoke" "src/hyperkar" "src/xtermkar" "${path_dir}/"
[ -f "${path_dir}/bk-extractor" ] && rm "${path_dir}/bk-extractor" ; \
[ ! -e "${path_dir}/bk-extractor" ] && ln -s "${system_bk_dir}/bashkaraoke_FILES/bashkaraoke_EXTRACTOR" "${path_dir}/bk-extractor"
#
#############################################
#

#5) in additional, let's copy README and license files into /usr/share/doc/bashkaraoke
cp LICENSE README ${DOCDIR}


#let's comment all the windows style installation dialog while packaging
#[ "${l}" = "IT" ] && ok_message "Installazione terminata \n con successo ! \n\n Grazie per aver installato \n Bash!Karaoke ! \n\n Puoi lanciarlo, \n in un terminale, \n digitando : \n \"bashkaraoke\" \n dopodiche', \n non dimenticarti \n di configurare \n il font... \n\n\n Divertiti !   ;-)"
#[ "${l}" = "EN" ] && ok_message "Bash!Karaoke successfully installed ! \n\n Thanks for installing \n Bash!Karaoke ! \n\n You would launch it, \n in a terminal, \n typing : \n \"bashkaraoke\" \n after that, \n don't forget \n to configure font...\n\n\n Enjoy !   ;-)" 
#

[ "${l}" = "IT" ] && echo -e "\n\nBash!Karaoke v.${BK_VERSION_NUMBER} installata \n con successo ! \n\nGrazie per aver installato \n Bash!Karaoke ! \n\n Puoi lanciarlo, \n in un terminale, \n digitando : \n \"bashkaraoke\" \n dopodiche', \n non dimenticarti \n di configurare \n il font... \n\n\n Divertiti !   ;-)"
[ "${l}" = "EN" ] && echo -e "\n\nBash!Karaoke v.${BK_VERSION_NUMBER} successfully installed ! \n\nThanks for installing \n Bash!Karaoke ! \n\n You would launch it, \n in a terminal, \n typing : \n \"bashkaraoke\" \n after that, \n don't forget \n to configure font...\n\n\n Enjoy !   ;-)"

clean_temp

